image: ubuntu:18.04

scan:jsc:
  tags:
    - x86_64
    - linux
  only:
    refs:
      - schedules
  before_script:
    - mkdir $CI_PROJECT_DIR/results
  script:
    - bash -x ./scan-build-webkit.sh $CI_PROJECT_DIR/results
  artifacts:
    paths:
      - $CI_PROJECT_DIR/results


